title: Min Myat Oo
subtitle: My Personal Blog
name: Min Myat Oo
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer specializing in NetSuite development, ERP systems,
  and enterprise solutions. Sharing insights on software architecture,
  cloud computing, and business automation.
baseurl: "" 
url: "https://minmyatoo.github.io"
repository: minmyatoo/minmyatoo.github.io
locale: "en-US"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# Site Author
author:
  name: "Min Myat Oo"
  avatar: "/assets/images/bio-photo.jpg" 
  bio: "NetSuite Specialist"
  location: "Singapore"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/minmyatoo"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/minmyatoo"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

# Archives
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Important: Replace navigation with these settings
include: ["_pages"]
atom_feed:
  path: # blank to disable feed icon

# Top Navigation
masthead_title: # leave empty for default site title
search: true
breadcrumbs: false

# Main Navigation Menu
minimal_mistakes_skin: "dark"
search: true
search_full_content: true
search_provider: lunr

# Define the main navigation menu
header:
  overlay_color: "#000"
  overlay_filter: "0.5"

# This is the correct way to define the main menu in minimal mistakes
main:
  - title: "About"
    url: /about/
  - title: "Posts"
    url: /posts/
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/

# Pagination
paginate: 7
paginate_path: /page:num/

# Analytics (optional)
# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"
#     anonymize_ip: false