# Site Settings
title: Min Myat Oo
subtitle: "Software Engineering & Cloud Solutions"
name: Min Myat Oo
description: >- 
  Experienced Software Engineer specializing in NetSuite development,
  cloud architecture, and enterprise solutions. Sharing insights on
  modern development practices and business automation.
locale: "en-US"
masthead_title: "Min Myat Oo"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mint"
breadcrumbs: true
words_per_minute: 200
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# Layout Settings
excerpt_separator: "<!--more-->"
classes:
  - wide
  - dark-theme

# Author Settings
author:
  name: "Min Myat Oo"
  avatar: "/assets/images/profile.jpg"
  bio: |
    🚀 NetSuite Solutions Architect
    💻 Full Stack Developer
    ☁️ Cloud Architecture Specialist
  location: "Singapore"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/minmyatoo"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "#"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "#"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:your.email@domain.com"

# Navigation
main:
  - title: "About"
    url: /about/
    description: "Learn more about my journey and expertise"
  - title: "Blog"
    url: /posts/
    description: "Technical articles and insights"
  - title: "Projects"
    url: /projects/
    description: "Featured work and case studies"
  - title: "Skills"
    url: /skills/
    description: "Technical expertise and capabilities"
  - title: "Contact"
    url: /contact/
    description: "Get in touch"

# Footer Configuration
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/minmyatoo"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "#"
  copyright: "© 2024 Min Myat Oo · Built with Jekyll & ❤️"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  skills:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      show_date: true
      header:
        overlay_filter: 0.5
        show_overlay_excerpt: true
      sidebar:
        nav: "recent-posts"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
      related: true
      sidebar:
        nav: "projects"
  # _skills
  - scope:
      path: "_skills"
      type: skills
    values:
      layout: single
      classes: wide
      author_profile: false
      share: false

# Comments
comments:
  provider: "giscus"
  giscus:
    repo_id: # your repo ID
    category_name: "Comments"
    category_id: # your category ID
    discussion_term: "pathname"
    reactions_enabled: 1
    theme: "dark_dimmed"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: # your tracking ID
    anonymize_ip: true

# SEO Settings
twitter:
  username: # your Twitter username
social:
  type: Person
  name: "Min Myat Oo"
  links:
    - "https://github.com/minmyatoo"
    - "https://linkedin.com/in/minmyatoo"

# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives

# Archive Settings
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Pagination
paginate: 9
paginate_path: /page:num/

# Optimization
sass:
  style: compressed
compress_html:
  clippings: all
  ignore:
    envs: development